[mypy]
strict = true
disable_error_code =
    attr-defined,
    no-untyped-call


[mypy-geometry_msgs.*]
ignore_missing_imports = true

[mypy-ament_copyright.*]
ignore_missing_imports = true

[mypy-ament_flake8.*]
ignore_missing_imports = true

[mypy-ament_pep257.*]
ignore_missing_imports = true
